logging:
  file.name: ./log/backend.log
  level:
    root: DEBUG

spring:
  datasource:
    url: jdbc:h2:file:./backend/database/db
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  jpa:
    # Set this property to true if you want to see the executed queries
    show-sql: false
    hibernate:
      ddl-auto: update
    # Allows to fetch lazy properties outside of the original transaction. Although this sounds helpful, the property
    # is disabled since it breaks the principle of least astonishment and leads to bad performance. The learn more,
    # follow this link: https://bit.ly/2LaX9ku
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

security:
  auth:
    header: Authorization
    prefix: "Bearer "
    login-uri: /login
    white-list:
      # Browser requests
      - /
      - /favicon.ico
      - /csrf
      # Swagger
      - /v2/api-docs
      - /swagger-resources/**
      - /webjars/**
      - /swagger-ui.html
      # H2
      - /h2-console/**
    cors-origins: "http://localhost:4200"
  jwt:
    secret: 4u7x!A%D*F-JaNdRgUkXp2s5v8y/B?E(H+KbPeShVmYq3t6w9z$C&F)J@NcQfTjW
    type: JWT
    issuer: ticketline16-backend
    audience: ticketline16-app
    # 12 hours in milliseconds
    expiration-time: 43200000

server.servlet.context-path: /v1

ticketline:
  seller:
    name: 'Ticketline'
    street: 'Musterstraße'
    housenr: '1'
    postalcode: '1010'
    city: 'Wien'
    country: 'Österreich'
    UID: 'ATU12345678'
